@startuml
title ExpenseService ICFG

start

:ExpenseService.createExpense(userId, request);

:validationService.getUserIfExists(userId);
:validationService.getCategoryIfExists(userId, request.category);

if (participants != null) then (yes)
  :for each participantId;
  :validationService.getFriendIfExists(userId, participantId);
endif

:create Expense entity;
:expenseRepository.save(expense);

if (participants not empty?) then (yes)
  :participantsCount = friends + 1;
  :shareAmount = amount / participantsCount;

  :for each friend;
  :create ExpenseParticipant;
  :expenseParticipantRepository.save();
endif

:return void;

stop
@enduml