@startuml
title ValidationService ICFG

start

:getUserIfExists(userId);

if (user exists?) then (yes)
  :return User;
else (no)
  :throw ResourceNotFoundException;
endif

---

:getCategoryIfExists(userId, categoryName);

if (categoryName != null) then (yes)
  if (category exists?) then (yes)
    :return Category;
  else (no)
    :throw ResourceNotFoundException;
  endif
endif

:return null;

stop
@enduml